# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 429)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 130, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 190, 113, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 250, 113, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 651, 331))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(30, 60, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.image_label = QtWidgets.QLabel(self.groupBox)
        self.image_label.setGeometry(QtCore.QRect(180, 50, 441, 251))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 20, 461, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_2.raise_()
        self.pushButton.raise_()
        self.image_label.raise_()
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(100, 350, 113, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(460, 350, 113, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸采集与识别"))
        self.pushButton_2.setText(_translate("MainWindow", "矩阵转换"))
        self.pushButton_3.setText(_translate("MainWindow", "人脸识别"))
        self.pushButton_4.setText(_translate("MainWindow", "人脸检测"))
        self.groupBox.setTitle(_translate("MainWindow", "主功能区"))
        self.pushButton.setText(_translate("MainWindow", "图像采集"))
        self.groupBox_2.setTitle(_translate("MainWindow", "摄像头预览框（USB或CSI总线设备） 仅供预览！"))
        self.pushButton_5.setText(_translate("MainWindow", "Refresh!"))
        self.pushButton_6.setText(_translate("MainWindow", "Quit!"))
